[project]
name = "i2cdgui"
version = "0.1.0"
description = "GUI for I2CDriver"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "usb-monitor",
    "i2cdriver==1.0.6",
    "pyside6==6.9",
    "pytide6 @ git+https://github.com/priimak/PyTide6.git@master"
]

[build-system]
requires = ["setuptools", "wheel", "setuptools-git-versioning"]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = true

[tool.setuptools.packages.find]
where = ["src"]

